# Generated by Django 5.1 on 2025-04-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import user_management.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('companyid', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'userType',
                    models.CharField(
                        choices=[('user', 'User'), ('realtor', 'Realtor')],
                        default='realtor',
                        max_length=10,
                    ),
                ),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.customuser',),
            managers=[
                ('objects', user_management.models.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.customuser',),
            managers=[
                ('objects', user_management.models.CustomerManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                (
                    'key',
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='custom_auth_token',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RealtorClient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_realtors',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'realtor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='realtor_clients',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    'ip_address',
                    models.GenericIPAddressField(blank=True, default='', null=True),
                ),
                (
                    'user_agent',
                    models.CharField(blank=True, default='', max_length=256),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='password_reset_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
        migrations.CreateModel(
            name='VerifyAccountToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    'ip_address',
                    models.GenericIPAddressField(blank=True, default='', null=True),
                ),
                (
                    'user_agent',
                    models.CharField(blank=True, default='', max_length=256),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='verify_account_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Verify Account Token',
                'verbose_name_plural': 'Verify Account Tokens',
            },
        ),
    ]
