# Generated by Django 5.0.3 on 2024-08-16 11:48

from django.db import migrations

import user_management.models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_management', '0002_admin_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_management.customuser',),
            managers=[
                ('objects', user_management.models.CustomerManager()),
            ],
        ),
    ]
