# Generated by Django 5.1 on 2025-04-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='userType',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='companyid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='custom_auth_tokens',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.CreateModel(
            name='SetPasswordToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    'realtor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='set_password_client_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='set_password_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Set Password Token',
                'verbose_name_plural': 'Set Password Tokens',
            },
        ),
    ]
