# Generated by Django 5.1 on 2025-04-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0004_rename_company_customuser_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_id',
            new_name='license_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
