# Generated by Django 5.1 on 2025-05-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0006_clientfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
