# Generated by Django 5.1 on 2025-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0007_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
