# Generated by Django 5.1 on 2025-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0008_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(
                blank=True, null=True, upload_to='profile_pictures/'
            ),
        ),
    ]
