# Generated by Django 5.1 on 2025-05-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0001_initial'),
        ('properties', '0009_alter_clientproperty_realtor_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chats',
                to='properties.realtorproperty',
            ),
        ),
    ]
