# Generated by Django 5.1 on 2025-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_alter_chat_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_chat_viewed_by_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
