# Generated by Django 5.1 on 2025-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deadline_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deadline_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_deadline_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
