# Generated by Django 5.1 on 2025-04-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('bidder_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
                (
                    'property_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='property_offers',
                        to='properties.property',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
