# Generated by Django 5.1 on 2025-04-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='open_house_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                (
                    'from_property',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='from_property_comparables',
                        to='properties.property',
                    ),
                ),
                (
                    'to_property',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='to_property_comparables',
                        to='properties.property',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Property Comparable',
                'verbose_name_plural': 'Property Comparables',
                'unique_together': {('from_property', 'to_property')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='comparables',
            field=models.ManyToManyField(
                through='properties.Comparable', to='properties.property'
            ),
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                (
                    'property_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='property_disclosures',
                        to='properties.property',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
