# Generated by Django 5.1 on 2025-04-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0003_property_deadlinedate_property_deadlinetime_and_more'),
        ('properties', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetail',
            name='redfin_url',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='zillow_url',
        ),
        migrations.AddField(
            model_name='property',
            name='redfin_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zillow_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='property_id',
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='property',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='property_details',
                to='properties.property',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
