# Generated by Django 5.1 on 2025-05-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0006_merge_20250430_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RelatorProperty',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_relator_properties',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'property',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relator_properties',
                        to='properties.property',
                    ),
                ),
                (
                    'relator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relator_relator_properties',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClientProperty',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_properties',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'relator_property',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='client_properties',
                        to='properties.relatorproperty',
                    ),
                ),
            ],
        ),
    ]
