# Generated by Django 5.1 on 2025-05-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            'properties',
            '0008_remove_clientproperty_relator_property_property_city_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='realtor_property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='realtor_properties',
                to='properties.realtorproperty',
            ),
        ),
    ]
