# Generated by Django 5.1 on 2025-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0009_alter_clientproperty_realtor_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
