# Generated by Django 5.1 on 2025-05-14 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0010_alter_disclosure_name'),
        ('properties', '0010_remove_propertymedia_image_property_listing_id_and_more'),
    ]

    operations = []
