# Generated by Django 5.1 on 2025-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0010_remove_propertymedia_image_property_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
