# Generated by Django 5.1 on 2025-05-15 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0011_alter_property_address'),
        ('properties', '0011_merge_20250514_1021'),
    ]

    operations = []
