# Generated by Django 5.1 on 2025-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0012_merge_20250515_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparable',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparable',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DisclosureFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to='disclosures/')),
                (
                    'disclosure',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='properties.disclosure',
                    ),
                ),
            ],
        ),
    ]
