# Generated by Django 5.1 on 2025-05-15 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0010_remove_offer_property_id_offer_realtor_property'),
        ('properties', '0012_merge_20250515_1052'),
    ]

    operations = []
