# Generated by Django 5.1 on 2025-05-16 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0013_comparable_additional_info_comparable_url_and_more'),
        ('properties', '0013_merge_20250515_1227'),
    ]

    operations = []
