# Generated by Django 5.1 on 2025-05-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0013_comparable_additional_info_comparable_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparable',
            name='from_property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='from_property_comparables',
                to='properties.realtorproperty',
            ),
        ),
        migrations.AlterField(
            model_name='comparable',
            name='to_property',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='to_property_comparables',
                to='properties.realtorproperty',
            ),
        ),
    ]
