# Generated by Django 5.1 on 2025-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0014_alter_comparable_from_property_and_more'),
        ('properties', '0014_merge_20250516_0738'),
    ]

    operations = []
