# Generated by Django 5.1 on 2025-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0015_merge_20250516_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='comparables',
        ),
        migrations.AddField(
            model_name='realtorproperty',
            name='comparables',
            field=models.ManyToManyField(
                through='properties.Comparable', to='properties.realtorproperty'
            ),
        ),
    ]
