# Generated by Django 5.1 on 2025-05-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0016_remove_property_comparables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='property_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='property_disclosures',
                to='properties.realtorproperty',
            ),
        ),
    ]
