# Generated by Django 5.1 on 2025-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0018_realtorproperty_is_added_for_comparable'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproperty',
            name='is_added_for_comparable',
            field=models.BooleanField(default=False),
        ),
    ]
