# Generated by Django 5.1 on 2025-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0019_clientproperty_is_added_for_comparable'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_property_viewed_by_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
