# Generated by Django 5.1 on 2025-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0020_property_is_property_viewed_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
