# Generated by Django 5.1 on 2025-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0021_alter_disclosure_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtorproperty',
            name='property_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
