# Generated by Django 5.1 on 2025-06-11 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0021_comparable_is_link_only_alter_comparable_to_property'),
        ('properties', '0022_realtorproperty_property_rating'),
    ]

    operations = []
