# Generated by Django 5.1 on 2025-06-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0023_merge_20250611_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contingencies_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtorproperty',
            name='is_property_toured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
